/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState, useRef, useEffect } from "react";
import gsap, { Expo } from "gsap";
import { emojify } from "node-emoji";
import styles from "../styles/Wish.module.css";

const Home: NextPage = () => {
  const { asPath } = useRouter();
  const [src, setSrc] = useState("/lydia2.png");
  const [wishHeadingText, setWishHeadingText] = useState(
    "Happy Birthday Lydia!"
  );
  const [chatText, setChatText] = useState(
    "Happy birthday to you!! Yeee! Many many happy blah..."
  );
  const query = asPath.split("?")[1] || "";
  const container = useRef<HTMLDivElement>(null);
  const one = useRef<HTMLDivElement>(null);
  const two = useRef<HTMLDivElement>(null);
  const three = useRef<HTMLDivElement>(null);
  const four = useRef<HTMLDivElement>(null);
  const greeting = useRef<HTMLDivElement>(null);
  const name = useRef<HTMLDivElement>(null);
  const greetingText = useRef<HTMLDivElement>(null);
  const text1 = useRef<HTMLDivElement>(null);
  const textInChatBox = useRef<HTMLDivElement>(null);
  const wishHeading = useRef<HTMLDivElement>(null);
  const wishText = useRef<HTMLDivElement>(null);
  const sendButtonLabel = useRef<HTMLDivElement>(null);
  const text2 = useRef<HTMLDivElement>(null);
  const text3 = useRef<HTMLDivElement>(null);
  const text4 = useRef<HTMLDivElement>(null);
  const text4Adjective = useRef<HTMLDivElement>(null);
  const text5Entry = useRef<HTMLDivElement>(null);
  const text5Content = useRef<HTMLDivElement>(null);
  const smiley = useRef<HTMLDivElement>(null);
  const bigTextPart1 = useRef<HTMLDivElement>(null);
  const bigTextPart2 = useRef<HTMLDivElement>(null);
  const outroText = useRef<HTMLDivElement>(null);
  const replayText = useRef<HTMLDivElement>(null);
  const outroSmiley = useRef<HTMLDivElement>(null);
  const tl = gsap.timeline();

  useEffect(() => {
    const ideaTextTrans = {
      opacity: 0,
      y: -20,
      rotationX: 5,
      skewX: "15deg",
    };

    const ideaTextTransLeave = {
      opacity: 0,
      y: 20,
      rotationY: 5,
      skewX: "-15deg",
    };
    fetch(`/api/details?${query}`)
      .then((res) => res.json())
      .then((data) => {
        const dataArr = Object.keys(data);
        dataArr.forEach((customData): any => {
          if (data[customData] !== "") {
            switch (customData) {
              case "wishHeading":
                setWishHeadingText(emojify(data[customData]));
                break;
              case "textInChatBox":
                setChatText(emojify(data[customData]));
                break;
              case "imagePath":
                setSrc(emojify(data[customData]));
                break;
              default:
                eval(customData).current.innerText = emojify(data[customData]);
            }
          }
        });
        setChatText(
          (cur) => `<span>${cur.split("").join("</span><span>")}</span>`
        );

        setWishHeadingText(
          (cur) => `<span>${cur.split("").join("</span><span>")}</span>`
        );
        // tl.to(container.current, 5, {
        //   visibility: "visible",
        // })
        tl.to(container.current, {
          visibility: "visible",
          duration: 0.1,
        }).to(one.current, {
          opacity: 0,
          y: 10,
          duration: 0.7,
        });
      })
      .catch((err) => console.log(err));
  }, [query, tl]);

  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="Happy-BirthDay" content="Happy-BirthDay" />
        <meta property="og:title" content="Happy-BirthDay App" />
        <meta property="og:type" content="website" />
        <meta
          property="og:url"
          content="https://happy-birthday-wish.herokuapp.com/"
        />
        <meta name="og:image" content="/desc.jpg" />
        {/* Preview Credit: https://unsplash.com/photos/-gDHgEcec6Q?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink */}
        <meta
          name="description"
          content="Happy birthday!"
          property="og:description"
        />

        <meta name="description" content="/desc.jpg" property="og:image" />
        <meta
          name="keywords"
          content="Birthday, HBD, Happy Birthday, Happy-BirthDay, Happy-BirthDay"
        />
        <meta name="author" content="KasRoudra" />
        <meta name="application-name" content="Happy-BirthDay" />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:site" content="@kasroudra" />
        <meta name="twitter:creator" content="@kasroudra" />
        <meta name="twitter:title" content="Happy-BirthDay" />
        <meta name="twitter:description" content="Happy birthday!" />
        <meta name="twitter:image" content="/desc.jpg" />
        <title>Happy Birthday!!! :)</title>

        <link rel="shortcut icon" type="image/png" href="/favicon.png" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.container} ref={container}>
          <div className={styles.one} ref={one}>
            <h1 className={styles.one}>
              <span ref={greeting}>Hey</span>
              <span ref={name}>Lydia</span>
            </h1>
            <p className={styles.two} ref={greetingText}>
              I really like your name btw!
            </p>
          </div>
          <div className={styles.three} ref={three}>
            <p ref={text1}>It's your birthday!!! :D</p>
          </div>
          <div className={styles.four} ref={four}>
            <div className={styles.textBox}>
              <p
                className={styles.hbdChatbox}
                dangerouslySetInnerHTML={{ __html: chatText }}
              ></p>
              <p className={styles.fakeBtn} ref={sendButtonLabel}>
                Send
              </p>
            </div>
          </div>
          <div className={styles.five}>
            <p className={styles.idea1} ref={text2}>
              That's what I was going to do.
            </p>
            <p className={styles.idea2} ref={text3}>
              But then I stopped.
            </p>
            <p className={styles.idea3}>
              <span ref={text4}>I realised, I wanted to do something</span>
              <strong ref={text4Adjective}>special</strong>.
            </p>
            <p className={styles.idea4} ref={text5Entry}>
              Because,
            </p>
            <p className={styles.idea5}>
              <span ref={text5Content}>You are Special</span>
              <span className={styles.smiley} ref={smiley}>
                :)
              </span>
            </p>
            <p className={styles.idea6}>
              <span ref={bigTextPart1}>S</span>
              <span ref={bigTextPart2}>O</span>
            </p>
          </div>
          <div className={styles.six}>
            <Image
              src={src}
              alt=""
              layout="fill"
              className={styles.lydiDp}
              priority={true}
            />
            <Image
              src="/hat.svg"
              alt=""
              priority
              layout="fill"
              className={styles.hat}
            />
            <div className={styles.wish}>
              <h3
                className={styles.wishHbd}
                dangerouslySetInnerHTML={{ __html: wishHeadingText }}
              ></h3>
              <h5 ref={wishText}>
                May the js.prototypes always be with you! ;)
              </h5>
            </div>
          </div>
          <div className={styles.seven}>
            <div className={styles.baloons} style={{ position: "relative" }}>
              <Image src="/ballon2.svg" alt="" layout="fill" />
              <Image src="/ballon1.svg" alt="" layout="fill" />
              <Image src="/ballon3.svg" alt="" layout="fill" />
              <Image src="/ballon1.svg" alt="" layout="fill" />
              <Image src="/ballon2.svg" alt="" layout="fill" />
              <Image src="/ballon3.svg" alt="" layout="fill" />
              <Image src="/ballon2.svg" alt="" layout="fill" />
              <Image src="/ballon3.svg" alt="" layout="fill" />
              <Image src="/ballon1.svg" alt="" layout="fill" />
              <Image src="/ballon2.svg" alt="" layout="fill" />
              <Image src="/ballon3.svg" alt="" layout="fill" />
              <Image src="/ballon2.svg" alt="" layout="fill" />
              <Image src="/ballon1.svg" alt="" layout="fill" />
              <Image src="/ballon3.svg" alt="" layout="fill" />
              <Image src="/ballon2.svg" alt="" layout="fill" />
              <Image src="/ballon3.svg" alt="" layout="fill" />
              <Image src="/ballon1.svg" alt="" layout="fill" />
              <Image src="/ballon2.svg" alt="" layout="fill" />
              <Image src="/ballon1.svg" alt="" layout="fill" />
              <Image src="/ballon3.svg" alt="" layout="fill" />
              <Image src="/ballon3.svg" alt="" layout="fill" />
              <Image src="/ballon1.svg" alt="" layout="fill" />
              <Image src="/ballon2.svg" alt="" layout="fill" />
              <Image src="/ballon3.svg" alt="" layout="fill" />
              <Image src="/ballon2.svg" alt="" layout="fill" />
              <Image src="/ballon1.svg" alt="" layout="fill" />
              <Image src="/ballon3.svg" alt="" layout="fill" />
              <Image src="/ballon2.svg" alt="" layout="fill" />
              <Image src="/ballon3.svg" alt="" layout="fill" />
              <Image src="/ballon1.svg" alt="" layout="fill" />
              <Image src="/ballon2.svg" alt="" layout="fill" />
              <Image src="/ballon1.svg" alt="" layout="fill" />
              <Image src="/ballon3.svg" alt="" layout="fill" />
            </div>
          </div>
          <div className={styles.eight}>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
              <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
              <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
              <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
              <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
              <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
              <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
              <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
              <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
              <circle cx="20" cy="20" r="20" />
            </svg>
          </div>
          <div className={styles.nine}>
            <p ref={outroText}>
              Okay, now come back and tell me if you liked it.
            </p>
            <p id="replay" ref={replayText}>
              Or click, if you want to watch it again.
            </p>
            <p className={styles.lastsmile} ref={outroSmiley}>
              :)
            </p>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
